name: unnatkisan
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluent_ui:
    git: https://github.com/bdlukaa/fluent_ui.git
  
  otp_text_field: ^1.1.3
  shared_preferences: ^2.0.20
  ionicons: ^0.2.2
  iconsax: ^0.0.8
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets\login_background.png
    - assets\Crop_Data.json
    - assets\schemes.json
    - assets\organic_farming.json
    - assets\equipments.json
    - assets\market_prices.json
